### ISSUE TITLE
Error with Blizzard UI

### ISSUE THREAD

**Issue by WoWEsper** [RaiderIO/raiderio-addon#225]
![WoWScrnShot_103022_161847](https://user-images.githubusercontent.com/117042774/199607558-59e65bcc-0f1a-4ade-a97d-7418285ad545.jpg)
Error message pop-up when using the Raider.io addon. There is a consistent locking of UI and occasionally crashing the game. This has been happening since the pre-patch launch, Add-on is UTD.
My Current Addons are:
Adibags
Angry Keystones
Annouce Interrupts
Auctionator
BattlegroundEnemies
Better Vendor Price
Better Wardrobe & Transmog
Capping Battleground Timers
Covenant Mission Success Estimates 
DBM
DBM - SpellTimers
Death Alerts
Details!
ElitismHelper
GatherMate2
HandyNotes
Hekili
Immersion
Maze Helper
MBB
Method Raid Tools
NPCScans
O Item Level
OPie
Pawn
Postal
SayAnnouncer
SellTrash
SimCraft
TomCat's Tours
WeakAuras
WorldQuest Tab
Zereth Mortis Puzzle Helper

**Comment by jahraphael** [comment]
*Edited: Simplified requests after more discussion on our side*

These types of errors (taint issues) are complicated to track down. The most helpful thing for us is to be able to reproduce the problem locally. However, it tends to be related to all the specific addons you have installed.

So can you please try the following:

1) Provide us a list of all the addons you have installed
2) Try updating all your addons and see if you can repro the problem
3) Provide us with information on any steps you take to reproduce the problem (where applicable)

Assuming the error continues to occur for you, we can then hopefully reproduce it here too and track down exactly what is going on.

**Comment by PsjKana** [comment]
I ran into this with following error message

2x [ADDON_ACTION_FORBIDDEN] AddOn 'RaiderIO' tried to call the protected function 'UseAction()'.
[string "@Interface/AddOns/!BugGrabber/BugGrabber.lua"]:480: in function <Interface/AddOns/!BugGrabber/BugGrabber.lua:480>
[string "=[C]"]: in function `UseAction'
[string "@Interface/FrameXML/SecureTemplates.lua"]:364: in function `handler'
[string "@Interface/FrameXML/SecureTemplates.lua"]:690: in function <Interface/FrameXML/SecureTemplates.lua:672>
[string "@Interface/FrameXML/SecureTemplates.lua"]:704: in function <Interface/FrameXML/SecureTemplates.lua:697>
[string "@Interface/FrameXML/SecureTemplates.lua"]:746: in function `SecureActionButton_OnClick'
[string "@Interface/FrameXML/ActionButton.lua"]:109: in function `TryUseActionButton'
[string "@Interface/FrameXML/MultiActionBars.lua"]:14: in function `MultiActionButtonDown'
[string "MULTIACTIONBAR4BUTTON8"]:2: in function <[string "MULTIACTIONBAR4BUTTON8"]:1>

**Comment by remikzu** [comment]
I have similar issue - when I press an action button from action bar that is not 1st or 2nd then I get similar popup. It gets fixed after reload though. Quite frustrating since it happens a lot in the raid and I have to reload on the pulltimer.

Script:

4x [ADDON_ACTION_BLOCKED] AddOn 'RaiderIO' tried to call the protected function 'OverrideActionBarButton5:SetAttribute()'.
[string "@Interface/AddOns/!BugGrabber/BugGrabber.lua"]:480: in function <Interface/AddOns/!BugGrabber/BugGrabber.lua:480>
[string "=[C]"]: in function `SetAttribute'
[string "@Interface/FrameXML/ActionButton.lua"]:355: in function `UpdatePressAndHoldAction'
[string "@Interface/FrameXML/ActionButton.lua"]:415: in function `Update'
[string "@Interface/FrameXML/ActionButton.lua"]:367: in function `UpdateAction'
[string "@Interface/FrameXML/ActionButton.lua"]:803: in function `OnEvent'
[string "@Interface/FrameXML/ActionButton.lua"]:216: in function <Interface/FrameXML/ActionButton.lua:213>

Locals:
Skipped (In Encounter)

**Comment by syntrixsystems** [comment]
3x [ADDON_ACTION_BLOCKED] AddOn 'RaiderIO' tried to call the protected function 'GetPlaystyleString()'.
[string "@!BugGrabber\BugGrabber.lua"]:519: in function <!BugGrabber\BugGrabber.lua:519>
[string "=[C]"]: in function `GetPlaystyleString'
[string "@FrameXML\LFGList.lua"]:3543: in function <FrameXML\LFGList.lua:3532>
[string "=[C]"]: in function `LFGListUtil_SetSearchEntryTooltip'
[string "@FrameXML\LFGList.lua"]:2629: in function <FrameXML\LFGList.lua:2626>
[string "=[C]"]: in function `pcall'
[string "@RaiderIO\core.lua"]:1069: in function `ExecuteWidgetHandler'
[string "@RaiderIO\core.lua"]:6012: in function <RaiderIO\core.lua:6007>
[string "=[C]"]: in function `Update'
[string "@Blizzard_Communities\CommunitiesMemberList.lua"]:382: in function `UpdateMemberList'
[string "@Blizzard_Communities\CommunitiesMemberList.lua"]:485: in function <...ddOns\Blizzard_Communities\CommunitiesMemberList.lua:478>
[string "=[C]"]: in function `Show'
[string "@FrameXML\UIParent.lua"]:3017: in function `SetUIPanel'
[string "@FrameXML\UIParent.lua"]:2901: in function `ShowUIPanel'
[string "@FrameXML\UIParent.lua"]:2730: in function <FrameXML\UIParent.lua:2726>
[string "=[C]"]: in function `SetAttribute'
[string "@FrameXML\UIParent.lua"]:3582: in function <FrameXML\UIParent.lua:3561>
[string "=[C]"]: in function `ShowUIPanel'
[string "@FrameXML\UIParent.lua"]:3543: in function `ToggleFrame'
[string "@FrameXML\UIParent.lua"]:1128: in function `ToggleCommunitiesFrame'
[string "@FrameXML\UIParent.lua"]:982: in function `ToggleGuildFrame'
[string "TOGGLEGUILDTAB"]:1: in function <[string "TOGGLEGUILDTAB"]:1>

**Comment by drakkai** [comment]
It happens to me too - a pop-up window appears as in the screenshot and one of the key bindings at a time (a random one) is locked until I reload the UI or disable the addon. I have following addons installed:
- OmniCC
- Pawn
- Threat Plates
- TLDR Missions
- TomCat's Tours
- TomTom
- World Quest Tracker
- Wowhead Quick Link
- Bagnon
- Better Wardrobe and Transmog
- DBM
- Details Damage Meter
- GatherMate2
- GTFO

**Comment by WoWEsper** [comment]
1. My Current Addons are:
> Adibags
> Angry Keystones
> Annouce Interrupts
> Auctionator
> BattlegroundEnemies
> Better Vendor Price
> Better Wardrobe & Transmog
> Capping Battleground Timers
> Covenant Mission Success Estimates
> DBM
> DBM - SpellTimers
> Death Alerts
> Details!
> ElitismHelper
> GatherMate2
> HandyNotes
> Hekili
> Immersion
> Maze Helper
> MBB
> Method Raid Tools
> NPCScans
> O Item Level
> OPie
> Pawn
> Postal
> SayAnnouncer
> SellTrash
> SimCraft
> TomCat's Tours
> WeakAuras
> WorldQuest Tab
> Zereth Mortis Puzzle Helper
2. I update everyday before logging into the game. 
3. To reproduce the problem all i have to do is go into dungeon or raid with IO active and when engaging a boss or adds it can pop up.

**Comment by jahraphael** [comment]
@WoWEsper @GitPSj @remikzu @Drakkai @syntrixsystems  - We've just pushed a new build of the addon with more fixes to help root out cases where the addon may be causing actions to be blocked due to taint issues.

Please upgrade to a version at `v202211072254` or higher and let us know if you continue to see any problems.

Thanks for the help in trying to nail these fixes down!

**Comment by DanielSpindler** [comment]
Same error without having other addons installed. Occasionaly cant use my Bag.

**Comment by DanielSpindler** [comment]
Still the Same Error. Tried it without any other addons on a New Windows 10 OS. Still the same error!

**Comment by jahraphael** [comment]
> Still the Same Error. Tried it without any other addons on a New Windows 10 OS. Still the same error!

Can you paste the text from the error or a screenshot of it?

Also what are the steps you are doing to trigger the error? It would be very helpful if you are able to record a video showing the steps needed to trigger the issue.
